# fly.toml app configuration file generated for sunshinesf on 2024-07-19T22:12:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csrf-demo'
primary_region = 'sjc'

[build]
[build.args]
GO_VERSION = '1.24.1'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[experimental]
cmd = ["/usr/bin/csrf-demo", "-domain=csrf.patrickod.com"]
